some fixes

diff --git a/mk-firecracker b/mk-firecracker
--- a/mk-firecracker
+++ b/mk-firecracker
@@ -1,45 +1,98 @@
 #!/bin/bash
 
-QMU_IMG=$2
+ID=$(id | awk '{ print $1; }' | cut -b 5-8 | sed 's/[^0-9]*//g')
+
+usage() {
+	echo -e "mk-firecracker -s <SIZE> -i <QCOW2_IMG> -p <ROOT_PART>"
+	echo -e "options:"
+	echo -e "\t-s : size of final ext4 file in GB (eg -s 4 == 4GB)"
+	echo -e "\t-i : QCOW2 image to transform"
+	echo -e "\t-p : Partition where the filesystem is kept in QCOW2_IMG"
+	echo -e "\n\texample:\n\t$ mk-firecracker -s 10 -i arch.qcow2 -p 3\n"
+}
+
+SIZE=""
+QEMU_IMG=""
+PART=""
+
+while [[ ! -z "$1" ]]; do
+	case "$1" in
+		-h|--help)
+			usage
+			exit 1
+			;;
+		-s|--size)
+			SIZE=$2
+			shift
+			;;
+		-i|--img)
+			QEMU_IMG=$2
+			shift
+			;;
+		-p|--partition)
+			PART=$2
+			shift
+			;;
+	esac
+	shift
+done
+
+if [[ $ID != "0" ]]; then
+	echo -e "Error: Must be root"
+	exit 1
+fi
+
+if [[ $SIZE == "" || $QEMU_IMG == "" || $PART == "" ]]; then
+	echo -e "ERROR: Missing parameter"
+	usage
+	exit 1
+else
+	echo -e "size = $SIZE image = $QEMU_IMG partition = $PART"
+fi
+
 BASE=`pwd`
 EXT=$BASE/ext4-dir
 
-sudo umount ext4-dir
-sudo umount raw-dir
+umount ext4-dir
+umount raw-dir
 rm -rf ext4-dir raw-dir
 mkdir ext4-dir raw-dir
 
 rm OS.ext4
-dd if=/dev/zero of=OS.ext4 bs=1G count=$1
+dd if=/dev/zero of=OS.ext4 bs=1G count=$SIZE
 mkfs.ext4 OS.ext4
 
-LOOP_0=`sudo losetup -f`
-sudo losetup -fP OS.ext4
-sudo mount $LOOP_0 ext4-dir
+LOOP_0=`losetup -f`
+echo "loop0 is $LOOP_0"
+losetup -fP OS.ext4
+mount $LOOP_0 ext4-dir
 
-LOOP_1=`sudo losetup -f`
+LOOP_1=`losetup -f`
+LOOP_1+="p$PART"
 
-isqemu=$(file $QMU_IMG | grep -i "qemu qcow2")
+echo "$LOOP_1"
+
+isqemu=$(file $QEMU_IMG | grep -i "qemu qcow2")
 if [[ ! -z "$isqemu" ]]; then
-	rm $2.raw
-	qemu-img convert -f qcow2 -O raw $2 $2.raw
-	QMU_IMG="$2.raw"
+	rm $QEMU_IMG.raw
+	qemu-img convert -f qcow2 -O raw $QEMU_IMG $QEMU_IMG.raw
+	QEMU_IMG="$QEMU_IMG.raw"
 fi
 
-sudo losetup -fP $QMU_IMG
-sudo mount $LOOP_1$3 raw-dir
+losetup -fP $QEMU_IMG
+mount "$LOOP_1" raw-dir
 
 cd raw-dir
 cd root
-sudo tar c . | sudo tar x -C $EXT
+tar c . | tar x -C $EXT
 cd $BASE
-sudo rm -rf ext4-dir/lost+found
-sudo rm ext4-dir/etc/fstab
-sudo touch ext4-dir/.autorelabel
+rm -rf ext4-dir/lost+found
+rm ext4-dir/etc/fstab
+touch ext4-dir/.autorelabel
 ls -l ext4-dir
 
-sudo umount raw-dir
-sudo umount ext4-dir
-sudo losetup -d $LOOP_1
-sudo losetup -d $LOOP_0
+umount raw-dir
+umount ext4-dir
+losetup -d $LOOP_1
+losetup -d $LOOP_0
 rm -rf raw-dir ext4-dir
